SELECT 
    C.COLUMN_NAME, C.COLUMN_TYPE, C.IS_NULLABLE, C.COLUMN_KEY, C.COLUMN_DEFAULT, C.EXTRA,
    T.TABLE_TYPE, T.ENGINE, T.TABLE_COLLATION
FROM INFORMATION_SCHEMA.COLUMNS C
JOIN INFORMATION_SCHEMA.TABLES T
    ON C.TABLE_NAME = T.TABLE_NAME AND C.TABLE_SCHEMA = T.TABLE_SCHEMA
WHERE C.TABLE_NAME = 'books' AND C.TABLE_SCHEMA = DATABASE();